server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
# TODO Localization
#  messages:
#    basename: lang/res
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false